---
- name: 删除/etc/hosts
  file:
    path: /etc/hosts
    state: absent
  become: yes
  become_user: root

- name: 添加回环地址到/etc/hosts中
  shell:
    echo {{ item }} >> /etc/hosts
  with_items:
    - 127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
    - ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
  become: yes
  become_user: root

- name: 添加到ip和主机名/etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "{{ item.ip }}"
    line: "{{ item.ip }} {{ item.node }}"
    state: present
  with_items:
    - "{{ ip_and_node }}"
  become: yes
  become_user: root

- name: 查看执行主机目录下是否存在公钥文件
  local_action:
    shell ls "{{ ssh_key_dir }}/authorized_keys.j2"
  run_once: yes
  register: info
  ignore_errors: yes

- name: 存在则删除本地公钥
  local_action:
    shell rm -rf "{{ ssh_key_dir }}/authorized_keys.j2"
  run_once: yes
  when: info is not failed

- name: 获取执行主机的公钥
  local_action:
    shell cat "{{ local_ssh_path }}/.ssh/id_rsa.pub"
  register: exec_ssh_info
  run_once: yes

- name: 接收执行主机公钥的值
  set_fact: exec_ssh_pub={{ exec_ssh_info.stdout }}
  run_once: yes

- name: 写入执行主机公钥
  local_action:
    shell echo {{ exec_ssh_pub }} >> "{{ ssh_key_dir }}"/authorized_keys.j2
  run_once: yes

- name: 获取远程主机的公钥
  shell: cat "{{ install_dir }}/.ssh/id_rsa.pub"
  register: ssh_info

- name: 接收远程主机公钥的值
  set_fact: ssh_pub={{ ssh_info.stdout }}

- name: 写入到本地
  local_action:
    shell echo {{ item }} >> "{{ ssh_key_dir }}"/authorized_keys.j2
  with_items:
    - "{{ ssh_pub }}"

- name: 分发到各个主机
  template:
    src: "{{ ssh_key_dir }}/authorized_keys.j2"
    dest: "{{ install_dir }}/.ssh/authorized_keys"
    group: "{{ group_name }}"
    owner: "{{ username }}"
    mode: 0600

- name: 删除本地公钥
  local_action:
    shell rm -rf "{{ ssh_key_dir }}/authorized_keys.j2"
  run_once: yes

- name: 添加主机信息到known_hosts
  shell: ssh-keyscan {{ item }} >> /root/.ssh/known_hosts
  with_items:
    - "{{ all_node }}"
  become: yes
  become_user: root